ci-success:
  name: ci
  if: ${{ success() }}
  needs:
    - checks
  runs-on: ubuntu-latest
  steps:
    - id: build
      name: Build
      run: |
        echo 'built'

    - name: CI succeeded
      run: exit 0
