name: Long tests
on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: check-build
        name: build
        run: |
          echo 'checked'
